# Generated by Django 2.0.3 on 2018-03-20 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20180320_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cemetery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_cemetery', to='website.Cemetery', verbose_name='Захоронение'),
        ),
        migrations.AlterField(
            model_name='person',
            name='cemetery_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_cemetery_actual', to='website.Cemetery', verbose_name='Актуальное захоронение'),
        ),
        migrations.AlterField(
            model_name='person',
            name='fio',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='person',
            name='fio_actual',
            field=models.CharField(blank=True, max_length=255, verbose_name='Актуальные ФИО'),
        ),
        migrations.AlterField(
            model_name='person',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_hospital', to='website.Hospital', verbose_name='Госпиталь'),
        ),
        migrations.AlterField(
            model_name='person',
            name='hospital_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_hospital_actual', to='website.Hospital', verbose_name='Актуальный госпиталь'),
        ),
        migrations.AlterField(
            model_name='person',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
    ]
