# Generated by Django 2.0.3 on 2018-03-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='header',
            field=models.IntegerField(default=1, verbose_name='Строки заголовка'),
        ),
        migrations.AddField(
            model_name='import',
            name='numbering',
            field=models.IntegerField(default=1, verbose_name='Колонки нумерации'),
        ),
        migrations.AlterField(
            model_name='import',
            name='name',
            field=models.CharField(default='import-20180322091946', max_length=255),
        ),
    ]
