# Generated by Django 2.0.3 on 2018-03-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20180322_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='delimiter',
            field=models.CharField(default=',', max_length=1, verbose_name='Разделитель'),
        ),
        migrations.AddField(
            model_name='import',
            name='quotechar',
            field=models.CharField(default='"', max_length=1, verbose_name='Символ строки'),
        ),
        migrations.AddField(
            model_name='person',
            name='year',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Год рождения'),
        ),
        migrations.AddField(
            model_name='person',
            name='year_actual',
            field=models.IntegerField(blank=True, null=True, verbose_name='Актуальный год рождения'),
        ),
        migrations.AlterField(
            model_name='import',
            name='name',
            field=models.CharField(default='import-20180322123432', max_length=255),
        ),
    ]
