# Generated by Django 2.0.3 on 2018-05-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20180322_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место жительства'),
        ),
        migrations.AddField(
            model_name='person',
            name='address_actual',
            field=models.CharField(blank=True, max_length=255, verbose_name='Актуальное место жительства'),
        ),
        migrations.AddField(
            model_name='person',
            name='born_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес рождения'),
        ),
        migrations.AddField(
            model_name='person',
            name='born_address_actual',
            field=models.CharField(blank=True, max_length=255, verbose_name='Актуальный адрес рождения'),
        ),
        migrations.AddField(
            model_name='person',
            name='born_region',
            field=models.CharField(blank=True, max_length=255, verbose_name='Регион (страна) рождения'),
        ),
        migrations.AddField(
            model_name='person',
            name='born_region_actual',
            field=models.CharField(blank=True, max_length=255, verbose_name='Актуальный регион (страна) рождения'),
        ),
        migrations.AddField(
            model_name='person',
            name='conscription_place',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место призыва'),
        ),
        migrations.AddField(
            model_name='person',
            name='conscription_place_actual',
            field=models.CharField(blank=True, max_length=255, verbose_name='Актуальное место призыва'),
        ),
        migrations.AddField(
            model_name='person',
            name='death_cause',
            field=models.CharField(blank=True, max_length=255, verbose_name='Причина смерти'),
        ),
        migrations.AddField(
            model_name='person',
            name='death_cause_actual',
            field=models.CharField(blank=True, max_length=255, verbose_name='Актуальная причина смерти'),
        ),
        migrations.AddField(
            model_name='person',
            name='death_date',
            field=models.CharField(blank=True, max_length=255, verbose_name='Дата смерти'),
        ),
        migrations.AddField(
            model_name='person',
            name='death_date_actual',
            field=models.DateTimeField(null=True, verbose_name='Актуальная дата смерти'),
        ),
        migrations.AddField(
            model_name='person',
            name='grave',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер могилы'),
        ),
        migrations.AddField(
            model_name='person',
            name='grave_actual',
            field=models.IntegerField(null=True, verbose_name='Актуальный номер могилы'),
        ),
        migrations.AddField(
            model_name='person',
            name='military_unit',
            field=models.CharField(blank=True, max_length=50, verbose_name='Часть'),
        ),
        migrations.AddField(
            model_name='person',
            name='military_unit_actual',
            field=models.CharField(blank=True, max_length=50, verbose_name='Актуальная часть'),
        ),
        migrations.AddField(
            model_name='person',
            name='position',
            field=models.CharField(blank=True, max_length=50, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='person',
            name='position_actual',
            field=models.CharField(blank=True, max_length=50, verbose_name='Актуальная должность'),
        ),
        migrations.AddField(
            model_name='person',
            name='rank',
            field=models.CharField(blank=True, max_length=50, verbose_name='Звание'),
        ),
        migrations.AddField(
            model_name='person',
            name='rank_actual',
            field=models.CharField(blank=True, max_length=50, verbose_name='Актуальное звание'),
        ),
        migrations.AddField(
            model_name='person',
            name='receipt_cause',
            field=models.CharField(blank=True, max_length=255, verbose_name='Причина поступления'),
        ),
        migrations.AddField(
            model_name='person',
            name='receipt_cause_actual',
            field=models.CharField(blank=True, max_length=255, verbose_name='Актуальная причина поступления'),
        ),
        migrations.AddField(
            model_name='person',
            name='receipt_date',
            field=models.CharField(blank=True, max_length=50, verbose_name='Дата поступления'),
        ),
        migrations.AddField(
            model_name='person',
            name='receipt_date_actual',
            field=models.DateTimeField(null=True, verbose_name='Актуальная дата поступления'),
        ),
        migrations.AddField(
            model_name='person',
            name='relatives',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Родственники'),
        ),
        migrations.AddField(
            model_name='person',
            name='relatives_actual',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Актуальные родственники'),
        ),
        migrations.AlterField(
            model_name='import',
            name='name',
            field=models.CharField(default='import-20180516142348', max_length=255),
        ),
    ]
