# Generated by Django 2.0.3 on 2018-05-16 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20180516_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='active_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.Import'),
        ),
        migrations.AddField(
            model_name='import',
            name='data_added',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='active_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.Import'),
        ),
        migrations.AlterField(
            model_name='import',
            name='name',
            field=models.CharField(default='import-20180516144655', max_length=255),
        ),
    ]
