# Generated by Django 2.0.3 on 2018-05-17 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20180516_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='name',
            field=models.CharField(default='import-20180517122206', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='cemetery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_cemetery', to='website.Cemetery', verbose_name='Кладбище'),
        ),
        migrations.AlterField(
            model_name='person',
            name='cemetery_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_cemetery_actual', to='website.Cemetery', verbose_name='Актуальное кладбище'),
        ),
        migrations.AlterField(
            model_name='person',
            name='death_date_actual',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Актуальная дата смерти'),
        ),
        migrations.AlterField(
            model_name='person',
            name='grave_actual',
            field=models.IntegerField(blank=True, null=True, verbose_name='Актуальный номер могилы'),
        ),
        migrations.AlterField(
            model_name='person',
            name='receipt_date_actual',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Актуальная дата поступления'),
        ),
    ]
