# Generated by Django 2.0.3 on 2018-05-17 12:25

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20180517_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='name',
            field=models.CharField(default=website.models.default_import_name, max_length=255),
        ),
    ]
