# Generated by Django 2.0.5 on 2018-05-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20180522_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='death_cause',
            field=models.TextField(blank=True, null=True, verbose_name='Причина смерти'),
        ),
        migrations.AlterField(
            model_name='person',
            name='death_cause_actual',
            field=models.TextField(blank=True, null=True, verbose_name='Актуальная причина смерти'),
        ),
        migrations.AlterField(
            model_name='person',
            name='receipt_cause',
            field=models.TextField(blank=True, null=True, verbose_name='Причина поступления'),
        ),
        migrations.AlterField(
            model_name='person',
            name='receipt_cause_actual',
            field=models.TextField(blank=True, null=True, verbose_name='Актуальная причина поступления'),
        ),
    ]
