# Generated by Django 2.0.5 on 2018-05-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20180530_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='military_unit',
            field=models.CharField(blank=True, max_length=255, verbose_name='Часть'),
        ),
        migrations.AlterField(
            model_name='person',
            name='military_unit_actual',
            field=models.CharField(blank=True, max_length=255, verbose_name='Актуальная часть'),
        ),
    ]
