# Generated by Django 2.0.5 on 2018-05-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20180530_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='import',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='cemetery',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
