# Generated by Django 2.0.6 on 2018-06-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20180531_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='grave',
            field=models.CharField(blank=True, max_length=255, verbose_name='Номер могилы'),
        ),
        migrations.AlterField(
            model_name='person',
            name='receipt_date',
            field=models.CharField(blank=True, max_length=255, verbose_name='Дата поступления'),
        ),
        migrations.AlterField(
            model_name='person',
            name='year',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Год рождения'),
        ),
    ]
