# Generated by Django 2.0.6 on 2018-06-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20180604_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='hospital',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Госпиталь'),
        ),
    ]
