# Generated by Django 2.0.6 on 2018-06-05 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_auto_20180605_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='active_import',
        ),
    ]
