# Generated by Django 2.0.6 on 2018-06-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_auto_20180605_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Место жительства'),
        ),
        migrations.AlterField(
            model_name='person',
            name='address_actual',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Актуальное место жительства'),
        ),
        migrations.AlterField(
            model_name='person',
            name='born_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес рождения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='born_address_actual',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Актуальный адрес рождения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='born_region',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Регион (страна) рождения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='born_region_actual',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Актуальный регион (страна) рождения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='conscription_place',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Место призыва'),
        ),
        migrations.AlterField(
            model_name='person',
            name='conscription_place_actual',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Актуальное место призыва'),
        ),
        migrations.AlterField(
            model_name='person',
            name='death_date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата смерти'),
        ),
        migrations.AlterField(
            model_name='person',
            name='fio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='person',
            name='fio_actual',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Актуальные ФИО'),
        ),
        migrations.AlterField(
            model_name='person',
            name='grave',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Расположение могилы'),
        ),
        migrations.AlterField(
            model_name='person',
            name='grave_actual',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Актуальное расположение могилы'),
        ),
        migrations.AlterField(
            model_name='person',
            name='military_unit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Часть'),
        ),
        migrations.AlterField(
            model_name='person',
            name='military_unit_actual',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Актуальная часть'),
        ),
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='person',
            name='position_actual',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Актуальная должность'),
        ),
        migrations.AlterField(
            model_name='person',
            name='rank',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Звание'),
        ),
        migrations.AlterField(
            model_name='person',
            name='rank_actual',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Актуальное звание'),
        ),
        migrations.AlterField(
            model_name='person',
            name='receipt_date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата поступления'),
        ),
        migrations.AlterField(
            model_name='person',
            name='relatives',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Родственники'),
        ),
        migrations.AlterField(
            model_name='person',
            name='relatives_actual',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Актуальные родственники'),
        ),
    ]
