# Generated by Django 2.0.6 on 2018-06-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_auto_20180605_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='fio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО (список, прочие источники)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='fio_actual',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Актуальные ФИО (список, прочие источники)'),
        ),
    ]
