# Generated by Django 2.0.6 on 2018-06-15 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_person_ontombstone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={},
        ),
    ]
