# Generated by Django 2.0.6 on 2018-11-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_auto_20180615_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='mia',
            field=models.BooleanField(default=False, verbose_name='Пропал без вести'),
        ),
    ]
