# Generated by Django 2.0.6 on 2018-11-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_person_mia'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='state',
            field=models.IntegerField(choices=[(0, 'Лечился'), (1, 'Пропал без вести'), (2, 'Убит')], default=0, verbose_name='Категория'),
        ),
    ]
