# Generated by Django 2.0.6 on 2018-11-21 19:30

from django.db import migrations, models


def migrate_mia_to_state(apps, schema_editor):
    Person = apps.get_model('website', 'Person')
    for person in Person.objects.all():
        if person.mia:
            person.state = 1
        person.save()


def migrate_state_to_mia(apps, schema_editor):
    Person = apps.get_model('website', 'Person')
    for person in Person.objects.all():
        person.mia = person.state == 1
        person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_person_state'),
    ]

    operations = [
        migrations.RunPython(migrate_mia_to_state, reverse_code=migrate_state_to_mia),
    ]
