# Generated by Django 2.0.6 on 2018-11-21 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_migrate_mia_to_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='mia',
        ),
    ]
