# Generated by Django 2.0.6 on 2019-01-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_auto_20181121_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='camp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Лагерь'),
        ),
        migrations.AddField(
            model_name='person',
            name='camp_actual',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Актуальный лагерь'),
        ),
        migrations.AddField(
            model_name='person',
            name='camp_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Лагерный номер'),
        ),
        migrations.AddField(
            model_name='person',
            name='camp_number_actual',
            field=models.IntegerField(blank=True, null=True, verbose_name='Актуальный лагерный номер'),
        ),
        migrations.AddField(
            model_name='person',
            name='date_of_captivity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата пленения'),
        ),
        migrations.AddField(
            model_name='person',
            name='date_of_captivity_actual',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Актуальная дата пленения'),
        ),
        migrations.AddField(
            model_name='person',
            name='place_of_captivity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Место пленения'),
        ),
        migrations.AddField(
            model_name='person',
            name='place_of_captivity_actual',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Актуальное место пленения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='state',
            field=models.IntegerField(choices=[(0, 'Лечился'), (1, 'Пропал без вести'), (2, 'Убит'), (3, 'Умер по пути в госпиталь'), (4, 'Погиб в плену')], default=0, verbose_name='Категория'),
        ),
    ]
