# Generated by Django 2.0.6 on 2019-01-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_auto_20190115_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='field_post',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Полевая почта'),
        ),
        migrations.AddField(
            model_name='person',
            name='field_post_actual',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Актуальная полевая почта'),
        ),
        migrations.AddField(
            model_name='person',
            name='lost_date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Связь прекращена'),
        ),
        migrations.AddField(
            model_name='person',
            name='lost_date_actual',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Актуальная дата прекращения связи'),
        ),
    ]
