# Generated by Django 2.0.6 on 2019-01-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_auto_20190115_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='grave',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Расположение могилы'),
        ),
        migrations.AlterField(
            model_name='person',
            name='grave_actual',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Актуальное расположение могилы'),
        ),
    ]
