# Generated by Django 2.0.6 on 2019-01-27 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_auto_20190127_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='cemetery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Cemetery', verbose_name='Мемориал'),
        ),
    ]
