# Generated by Django 2.0.6 on 2019-02-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_auto_20190127_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, 'Лечился'), (1, 'Пропал без вести'), (2, 'Убит'), (3, 'Умер по пути в госпиталь'), (4, 'Погиб в плену')], default=0, null=True, verbose_name='Категория'),
        ),
    ]
