# Generated by Django 2.0.6 on 2019-03-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_auto_20190204_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, 'Лечился'), (1, 'Пропал без вести'), (2, 'Убит'), (3, 'Умер по пути в госпиталь'), (4, 'Погиб в плену')], default=None, null=True, verbose_name='Категория'),
        ),
    ]
